# .github/workflows/wade.yml

name: WADE Live (GHA Edition)

on:
  schedule:
    # Runs every 2 minutes from 11am–11pm PT (18:00–06:00 UTC)
    - cron: '*/2 18-23 * * *'
    - cron: '*/2 0-6 * * *'
  workflow_dispatch:
    # Allows manual triggering

jobs:
  wade-live:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run WADE (GHA Mode)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: |
          python gha_main.py

